Genericmigration
FusionAuth/fusionauth-import-scripts pull request #21
Opened 2024-04-10 10:53 UTC by sixhobbits

2024-09-09 16:50 UTC, alex-fusionauth requested changes
@sixhobbits  There are a couple small changes on the Docker image but this paired well with the guide 😄

2024-09-09 16:50 UTC, alex-fusionauth commented on generic/fusionAuthDockerFiles/docker-compose.yml
> +    image: fusionauth/fusionauth-app:1.48.3
```suggestion
    image: fusionauth/fusionauth-app:latest
```

2024-09-09 16:50 UTC, alex-fusionauth commented on generic/fusionAuthDockerFiles/docker-compose.yml
> +version: '3'
No version needed
```suggestion

```

2024-09-12 17:35 UTC, alex-fusionauth commented
@sixhobbits conflicts please 🙏

2024-09-13 08:35 UTC, sixhobbits commented
@alex-fusionauth fixed

2024-09-13 12:05 UTC, merged